CryptoApp/config/routes.rb
Rails.application.routes.draw do
  resources :wallet_coins
  get 'home/index'
  get '/wallets/add', to: 'wallet_coins#create', as: 'add_wallet_coin'
  get '/wallets/add_usd', to: 'wallet_coins#add_usd', as: 'add_usd_wallet_coin'
  resources :coins
  resources :wallets
  resources :transactions

  
  root to: "home#index"
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

CryptoApp/app/models/wallet_coin.rb
class WalletCoin < ApplicationRecord
  belongs_to :wallet ,foreign_key: 'wallet_id'
  belongs_to :coin, foreign_key: 'coin_id'

  def to_s
    "Coin: #{self.api_key}, Amount: #{amount}"
  end

  def api_key
    coin.api_key
  end

  def api_name
    coin.api_name
  end
end

CryptoApp/app/controllers/wallet_coins_controller.rb
class WalletCoinsController < ApplicationController
  before_action :set_wallet_coin, only: %i[ show edit update destroy ]
  
  # GET /wallet_coins or /wallet_coins.json
  def index
    @wallet_coins = current_user.wallet.wallet_coins
  end

  # GET /wallet_coins/1 or /wallet_coins/1.json
  def show
  end

  # GET /wallet_coins/new
  def new
    @wallet_coin = WalletCoin.new
    @selectiveCoins = Coin.get_selective_coins()
  end

  # GET /wallet_coins/1/edit
  def edit
  end

  # POST /wallet_coins or /wallet_coins.json
  def create
    coin = Coin.retrieve_from_api(wallet_coin_params["coin_apikey"])
    new_wallet_coin_params = wallet_coin_params.merge(wallet_id: current_user.wallet.id, coin_id: coin).except(:coin_apikey)
    @wallet_coin = WalletCoin.new(new_wallet_coin_params)

    respond_to do |format|
      if @wallet_coin.save
        format.html { redirect_to @wallet_coin, notice: "Wallet coin was successfully created." }
        format.json { render :show, status: :created, location: @wallet_coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wallet_coin.errors, status: :unprocessable_entity }
      end
    end
  end


  def save_USDs
    #new_wallet_coin_params = wallet_coin_params.merge(wallet_id: current_user.wallet.id, coin_id: Coin.usd.id).except(:coin_apikey)
    #@wallet_coin = WalletCoin.new(new_wallet_coin_params)
    puts "MIRA ACA ABAJOOOOOOO!!!"
    puts Coin.usd.id
    @wallet_coin = current_user.wallet.retrieve_WCoin(Coin.usd)
    @wallet_coin.amount = @wallet_coin.amount + 0
    puts wallet_coin_params

    respond_to do |format|
      if @wallet_coin.save
        format.html { redirect_to @wallet_coin, notice: "You have added your USDs successfully." }
        format.json { render :show, status: :created, location: @wallet_coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wallet_coin.errors, status: :unprocessable_entity }
      end
    end
  end


  def add_usd
    render html: "wallet_coins/add_usd"
    render json: @wallet_coin

  end

  # PATCH/PUT /wallet_coins/1 or /wallet_coins/1.json
  def update
    respond_to do |format|
      if @wallet_coin.update(wallet_coin_params)
        format.html { redirect_to @wallet_coin, notice: "Wallet coin was successfully updated." }
        format.json { render :show, status: :ok, location: @wallet_coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wallet_coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallet_coins/1 or /wallet_coins/1.json
  def destroy
    @wallet_coin.destroy
    respond_to do |format|
      format.html { redirect_to wallet_coins_url, notice: "Wallet coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet_coin
      @wallet_coin = WalletCoin.find(9)
      #@wallet_coin = WalletCoin.find(params[:id])
      @selectiveCoins = Coin.get_selective_coins()
    end

    # Only allow a list of trusted parameters through.
    def wallet_coin_params
      params.fetch(:wallet_coin, {}).permit('wallet_id', 'coin_apikey','amount')
    end
end

CryptoApp/app/helpers/wallet_coins_helper.rb
module WalletCoinsHelper
end

CryptoApp/app/views/wallet_coins/_form.html.erb
<%= form_with(model: wallet_coin) do |form| %>
  <% if wallet_coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallet_coin.errors.count, "error") %> prohibited this wallet_coin from being saved:</h2>

      <ul>
        <% wallet_coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :coin_apikey, "Coin: "%>
    <%= form.select :coin_apikey, @selectiveCoins, include_blank: 'Select One'%>
  </div>

  <div class="field">
    <%= form.label :amount, "Amount: " %>
    <%= form.number_field :amount, step: :any %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

CryptoApp/app/views/wallet_coins/add_usd.html.erb
<h1>Add USD!!!!! :)</h1>

<%= render 'form', wallet_coin: @wallet_coin %>

<%= link_to 'Back', wallets_path %>

CryptoApp/app/views/wallet_coins/edit.html.erb
<h1>Editing Wallet Coin</h1>

<%= render 'form', wallet_coin: @wallet_coin %>

<%= link_to 'Show', @wallet_coin %> |
<%= link_to 'Back', wallet_coins_path %>

CryptoApp/app/views/wallet_coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wallet Coins</h1>
<% if @wallet_coins.empty? %>
  <p> You have no coins.</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @wallet_coins.each do |wallet_coin| %>
        <% if not wallet_coin.nil? %>
        <tr>
          <td>Name: <%= wallet_coin.api_key %> </td>
          <td>Abr: <%= wallet_coin.api_name %> </td>
          <td>Amount: <%= wallet_coin.amount %> </td>
          <td><%= link_to 'Show', wallet_coin %></td>
          <td><%= link_to 'Edit', edit_wallet_coin_path(wallet_coin) %></td>
          <td><%= button_to 'Destroy', wallet_coin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>

  </table>
<% end %>

<br>

<%= link_to 'Add Wallet Coin', new_wallet_coin_path %>
<%= link_to 'Wallet', wallets_path %>

CryptoApp/app/views/wallet_coins/new.html.erb
<h1>Add Wallet Coin</h1>

<%= render 'form', wallet_coin: @wallet_coin %>

<%= link_to 'Back', wallet_coins_path %>

CryptoApp/app/views/wallet_coins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_wallet_coin_path(@wallet_coin) %> |
<%= link_to 'Back', wallet_coins_path %>