CryptoApp/config/routes.rb
Rails.application.routes.draw do
  resources :wallet_coins
  get 'home/index'
  get '/wallets/add', to: 'wallet_coins#create', as: 'add_wallet_coin'
  get '/wallets/add_usd', to: 'wallet_coins#add_usd', as: 'add_usd_wallet_coin'
  resources :coins
  resources :wallets
  resources :transactions

  
  root to: "home#index"
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

CryptoApp/app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user,foreign_key: 'user_id'
  has_many :transactions, inverse_of: :wallet
  has_many :wallet_coins, inverse_of: :wallet


  def retrieve_WCoin(coin)
    if self.wallet_coins.exists?(coin_id: coin.id)
      self.wallet_coins.find_by(coin_id: coin.id)
    else
      newWC = WalletCoin.create(wallet_id: self.id, coin_id: coin.id, amount: 0)
    end
  end
  
  def validate_transaction(cSold, csAmount)
    cs = retrieve_WCoin(cSold)
    if cs.amount - cSAmount < 0
      return true
    end
  end
  def update_coins_after_transaction_new(cBough, cBAmount, cSold, cSAmount)
    cs = retrieve_WCoin(cSold)
    if cs.amount - cSAmount < 0
      puts "jaja"      #Como le aviso al usuario que no le alcanza?
      return false
    else
      cs.amount = cs.amount - cSAmount
    end

    cb = retrieve_WCoin(cBough)
    cb.amount = cb.amount + cBAmount

    cs.save()
    cb.save()
    
  end


  def downgrade_former_values(cBought, cB_amount, cSold, cS_amount)
    cb = retrieve_WCoin(cBought)
    cs = retrieve_WCoin(cSold)

    cb.amount = cb.amount - cB_amount
    cs.amount = cs.amount + cS_amount

    cs.save()
    cb.save()

  end

end

CryptoApp/app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :set_wallet, only: %i[ show edit update destroy ]

  #TODO limitar operaciones que se pueden hacer sobre una billetera


  # GET /wallets or /wallets.json
  def index
    @wallet = current_user.wallet
  end

  # GET /wallets/1 or /wallets/1.json
  def show
  end

  # GET /wallets/new
  # def new
  #   @wallet = Wallet.new
  # end

=begin
  # GET /wallets/1/edit
  def edit
  end
=end

  # POST /wallets or /wallets.json
=begin
  def create
    if current_user.id != nil
      @wallet = Wallet.new(wallet_params)
      end
    respond_to do |format|
      if @wallet.save
        format.html { redirect_to @wallet, notice: "Wallet was successfully created." }
        format.json { render :show, status: :created, location: @wallet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end
=end

=begin
  # PATCH/PUT /wallets/1 or /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to @wallet, notice: "Wallet was successfully updated." }
        format.json { render :show, status: :ok, location: @wallet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1 or /wallets/1.json
  def destroy
    @wallet.destroy
    respond_to do |format|
      format.html { redirect_to wallets_url, notice: "Wallet was successfully destroyed." }
      format.json { head :no_content }
    end
  end
=end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = Wallet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wallet_params
      params.fetch(:wallet, {})
    end
end

CryptoApp/app/helpers/wallets_helper.rb
module WalletsHelper
end

CryptoApp/app/views/wallets/_form.html.erb
<%= form_with(model: wallet) do |form| %>
  <% if wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% wallet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

CryptoApp/app/views/wallets/edit.html.erb
<h1>Editing Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Show', @wallet %> |
<%= link_to 'Back', wallets_path %>

CryptoApp/app/views/wallets/index.html.erb
<h1>Your wallet</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% if @wallet.wallet_coins.empty?%>
    <p> You have no coins.</p>
  <% else %>
    <p>Coins:</p>
    <% @wallet.wallet_coins.each do |wc| %>
      <tr>
        <td> <%= wc %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Transaction', new_transaction_path %>
<%= link_to 'Add Coins', new_wallet_coin_path	 %>
<%= link_to 'Add USD', add_usd_wallet_coin_path	 %>

CryptoApp/app/views/wallets/new.html.erb
<h1>New Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Back', wallets_path %>

CryptoApp/app/views/wallets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_wallet_path(@wallet) %> |
<%= link_to 'Back', wallets_path %>