CryptoApp/config/routes.rb
Rails.application.routes.draw do
  resources :wallet_coins
  get 'home/index'
  get '/wallets/add', to: 'wallet_coins#create', as: 'add_wallet_coin'
  get '/wallets/add_usd', to: 'wallet_coins#add_usd', as: 'add_usd_wallet_coin'
  resources :coins
  resources :wallets
  resources :transactions

  
  root to: "home#index"
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

CryptoApp/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = current_user.wallet.transactions

  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @selectiveCoins = Coin.get_selective_coins()
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    cb = Coin.retrieve_from_api(transaction_params["CB_apikey"])
    cs = Coin.retrieve_from_api(transaction_params["CS_apikey"])

    @transaction = Transaction.new(transaction_params.merge(wallet_id: current_user.wallet.id, CBought_id: cb, CSold_id: cs))

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    cb = Coin.retrieve_from_api(transaction_params["CB_apikey"])
    cs = Coin.retrieve_from_api(transaction_params["CS_apikey"])

    respond_to do |format|
      if @transaction.update_values(transaction_params.merge(wallet_id: current_user.wallet.id, CBought_id: cb, CSold_id: cs))
        format.html { redirect_to @transaction, notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    respond_to do |format|
      if @transaction.destroy
        format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end

    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
      @selectiveCoins = Coin.get_selective_coins()
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.fetch(:transaction, {}).permit('wallet_id', 'CB_apikey','CB_value', 'CB_amount', 'CS_apikey', 'CS_value', 'CS_amount', 'date')
    end
end

CryptoApp/app/helpers/transactions_helper.rb
module TransactionsHelper
  class NewTransactionValidator < ActiveModel::Validator
    def validate(record)
      current_user.wallet.validate_transaction(record.CSold, record.CS_Amount)
    end
  end
end

CryptoApp/app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :CB_apikey, "You bought: "%>
    <%= form.select :CB_apikey, @selectiveCoins, :required => true, include_blank: 'Select One'%>
  </div>

  <div class="field">
    <%= form.label :CB_value, "Value: " %>
    <%= form.number_field :CB_value, step: :any, :required => true %>
  </div>

  <div class="field">
    <%= form.label :CB_amount, "Amount: " %>
    <%= form.number_field :CB_amount, step: :any, :required => true %>
  </div>

  <div class="field">
    <%= form.label :CS_apikey, "You sold: " %>
    <%= form.select :CS_apikey, @selectiveCoins, include_blank: 'Select One', :required => true%>
  </div>

  <div class="field">
    <%= form.label :CS_value, "Value: " %>
    <%= form.number_field :CS_value, step: :any, :required => true %>
  </div>

  <div class="field">
    <%= form.label :CS_amount, "Amount: " %>
    <%= form.number_field :CS_amount, step: :any, :required => true %>
  </div>

  <div class="field">
    <%= form.label :date, "Date: " %>
    <%= form.date_field :date, :required => true, max: Date.today %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

CryptoApp/app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

CryptoApp/app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions of user <%= current_user.email %></h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= button_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

CryptoApp/app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

CryptoApp/app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>